hwi_oauth:
    connect:
        account_connector: tecspro_user_provider
    firewall_names:
        - 'main'
    fosub:
        username_iterations: 30
        properties:
            facebook: facebook_id

    resource_owners:
        facebook:
            type:                facebook
            client_id:           %tecspro_face_api_client_id%
            client_secret:       %tecspro_face_api_client_secret%
            options:
                display: popup #dialog is optimized for popup window
                auth_type: rerequest # Re-asking for Declined Permissions
            scope:         "email, publish_actions, manage_pages"
            infos_url:     "https://graph.facebook.com/me?fields=name,email"
            # paths:
            #     email:          email
            #     profilepicture: picture.data.url