parameters:
    tecspro_user_provider.class: Tecspro\Bundle\ApiPostBundle\Security\Core\User\FOSUBUserProvider

services:
    tecspro_facebook_api:
        class: Tecspro\Bundle\ApiPostBundle\Services\FacebookApi
        arguments:
            - "@service_container"
            - "@doctrine.orm.entity_manager"
#provider security facebook
    tecspro_user_provider:
        class: %tecspro_user_provider.class%
        arguments: ['@fos_user.user_manager', { facebook: facebook_id }]